/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controlador;

import static Controlador.ControladorQuincunce.cata;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author dms
 */
public class Home extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jB_Pascal = new javax.swing.JButton();
        jB_Galton = new javax.swing.JButton();
        jSP_Filas = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Triangulero");
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Pascal.setText("Triángulo Pascal");
        jB_Pascal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PascalActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jB_Pascal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, 40));

        jB_Galton.setText("Aparato de Galton");
        jB_Galton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GaltonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jB_Galton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 180, 40));

        jSP_Filas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jLayeredPane1.add(jSP_Filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 50, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filas:");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Triangulero");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controlador/559c9bdfb0fe90a55d3ed6a7ce2f93b8.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_PascalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PascalActionPerformed
        int filas = (int)jSP_Filas.getValue();
        ControladorPascal ventanaPascal = new ControladorPascal(filas);
        ventanaPascal.setVisible(true);
    }//GEN-LAST:event_jB_PascalActionPerformed

    private void jB_GaltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GaltonActionPerformed
        int filas = (int)jSP_Filas.getValue();
        ControladorQuincunce ventanaPascal = new ControladorQuincunce(filas);
        ventanaPascal.setVisible(true);
        ventanaPascal.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        ventanaPascal.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent event) {
            try{
                cata.stop();
            }
            catch(Exception e){
                
            }
            exitProcedure(ventanaPascal);
        }
    });
    }//GEN-LAST:event_jB_GaltonActionPerformed

    public void exitProcedure(JFrame j) {
    j.dispose();
    //System.exit(0);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Galton;
    private javax.swing.JButton jB_Pascal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSpinner jSP_Filas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
